### ISSUE TITLE
Somfy RTS Remote Control Listening

### ISSUE THREAD

**Issue by XDECO** [devmel/hass_airsend-addon#4]
I would like to know if it is possible to be able to "listen" to my Somfy RTS remote control so that the AirsendDuo can update the command that has just been sent on HA? which allows me to know if the shutters are open or closed when the command is sent from a local remote control.

**Comment by jouralexandre** [comment]
Hello,
There's a first integration of permanent listening under HA, an example is here: [GitHub link](https://github.com/devmel/hass_airsend/blob/master/airsend.example.yaml).

``` yaml
AirSend duo:
  type: 0
  spurl: !secret spurl
  sensors: 0
  bind: 1 #433Mhz generic
  refresh: 300
```

The "auto_include" parameter of the addon is used to add the decoded probes in order to find yours, then deactivate this parameter.

Best regards.
